### ISSUE TITLE
Date field not displaying correctly 

### ISSUE THREAD

**Issue by DmitriyMalayev** [karakum-team/kotlin-mui-showcase#13]
![image](https://user-images.githubusercontent.com/56614284/202514398-2720db59-417e-49a7-baa3-fc0efb7c911f.png) Before clicking

![image](https://user-images.githubusercontent.com/56614284/202514417-2abb65d4-60ef-4f88-ba7f-13f62c5e7be9.png)After clicking

![image](https://user-images.githubusercontent.com/56614284/202514445-7b27dc32-890c-4048-b60c-bc488e9afaf3.png)

Current behavior 😯
Date field label overlaps

Expected behavior 🤔
Date field and placeholder look elegantly together

Context 🔦
Input starting and ending bill date

**Comment by DmitriyMalayev** [comment]
**Resolved**

```
TextField {
    sx {
        width = 40.pct
    }
    label = ReactNode("Start Day")
    variant = FormControlVariant.outlined
    onClick = {
        val target = it.target as dom.html.HTMLInputElement
        target.type = InputType.date.toString()
    }
    onBlur = {
        val target = it.target as dom.html.HTMLInputElement
        target.type = InputType.text.toString()
    }
}
```

**Comment by aerialist7** [comment]
Hi @DmitriyMalayev, this is a bug of the MUI Material UI library. 
Please create an issue here https://github.com/mui/material-ui/issues

P.S. Also you can use 'Date Pickers' instead
- [Documentation](https://mui.com/x/react-date-pickers/getting-started/)
- [Kotlin Wrappers](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-mui/src/main/generated/muix/pickers)
- [Kotlin MUI Showcase](https://github.com/karakum-team/kotlin-mui-showcase/blob/main/src/main/kotlin/team/karakum/components/showcases/Pickers.kt)
