### ISSUE TITLE
browserDevelopmentRun broken

### ISSUE THREAD

**Issue by mikedawson** [karakum-team/kotlin-mui-showcase#17]
Expected result:

If you run the browserDevelopmentRun task, then it the browser should open on port 8080 and the showcase should load

```
./gradlew browserDevelopmentRun
```

Observed result:

Blank screen. No error messages on console. Tested on Firefox and Chrome. Using the build/distribution output works fine. 

![Screenshot from 2023-03-26 15-34-10](https://user-images.githubusercontent.com/4280622/227773035-ed07fac3-5c58-4a8e-8d01-25b657dd0f59.png)

**Comment by aerialist7** [comment]
Hi @mikedawson,

0. Update to the latest commit
1. Cleanup builds - `./gradlew clean`
2. Stop daemons - `./gradlew --stop`
3. Start dev - `./gradlew run`

It should help.
Please notify me about the result.

**Comment by aerialist7** [comment]
@mikedawson, closing it as resolved
