### ISSUE TITLE
Request Help～

### ISSUE THREAD

**Issue by Omooo** [karakum-team/kotlin-mui-showcase#18]
hello~
I want to ask if you can add a showcase of the following table classes (such as Line chart)?
Thanks.

**Comment by aerialist7** [comment]
@Omooo, you are right, there are no chart libraries in [kotlin-wrappers](https://github.com/JetBrains/kotlin-wrappers).
Probably you should pick a library that you need and write Kotlin declarations yourself. I recommend this one - [Tanstack React Charts](https://react-charts.tanstack.com/). It is very useful and also there are a bunch of other Tanstack libraries in Kotlin Wrappers such as 
 * Tanstack Query - [kotlin-tanstack-react-query](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-tanstack-react-query)
 * Tanstack React Table - [kotlin-tanstack-react-table](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-tanstack-react-table)
 * Tanstack React Virtual - [kotlin-tanstack-react-virtual](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-tanstack-react-virtual)
 
For information about how to create Kotlin declarations for JS libraries, you can write here to the corresponding Slack channel - ["kotlinlang #react"](https://kotlinlang.slack.com/archives/C5ZTZ6ER0)

P.S. I hope that someone who wants to collect all libraries from Tanstack will help you
