### ISSUE TITLE
Adaptive Stylization

### ISSUE THREAD

**Issue by aerialist7** [karakum-team/kotlin-mui-showcase#5]
Need to improve "Kotlin MUI Showcase" stylization to get adaptive stylization for
- mobile
- tablet
- desktop 

Link to check on mobile/tablet - https://karakum-team.github.io/kotlin-mui-showcase/

**Comment by vie10** [comment]
![image](https://user-images.githubusercontent.com/81972035/152676385-856a91e9-0d38-44a9-be66-c0891182f29e.png)

Seems there is required an another switcher of showcases for phone

**Comment by aerialist7** [comment]
@vie10, may be.
First of all we need to find cool analogues to understand how we will reorganize app layout for mobiles

**Comment by vie10** [comment]
I've a concept. What do you think about it?
![image](https://user-images.githubusercontent.com/81972035/152684784-c6fabc66-42a0-4a2c-bfb8-9dc217972960.png)
![image](https://user-images.githubusercontent.com/81972035/152684786-51578020-7522-4ed6-abac-ca50161d3857.png)

**Comment by aerialist7** [comment]
> I've a concept. What do you think about it?

I think we can use `SwipeableDrawer` instead of standard one. See https://mui.com/components/drawers/#swipeable-edge

Now I've added Grid layout. So we need something like this
https://codepen.io/flaviocopes/pen/JZWOEK

When screen width is large - we use `Drawer`, else `SwipeableDrawer`.

You can do it if you have a time.

Note: Media queries are very helpful here.

**Comment by vie10** [comment]
> > I've a concept. What do you think about it?
> 
> 
> 
> I think we can use `SwipeableDrawer` instead of standard one. See https://mui.com/components/drawers/#swipeable-edge
> 
> 
> 
> Now I've added Grid layout. So we need something like this
> 
> https://codepen.io/flaviocopes/pen/JZWOEK
> 
> 
> 
> When screen width is large - we use `Drawer`, else `SwipeableDrawer`.
> 
> 
> 
> You can do it if you have a time.
> 
> 
> 
> Note: Media queries are very helpful here.

I'll try it tomorrow

**Comment by vie10** [comment]
> > I've a concept. What do you think about it?
> 
> I think we can use `SwipeableDrawer` instead of standard one. See https://mui.com/components/drawers/#swipeable-edge
> 
> Now I've added Grid layout. So we need something like this https://codepen.io/flaviocopes/pen/JZWOEK
> 
> When screen width is large - we use `Drawer`, else `SwipeableDrawer`.
> 
> You can do it if you have a time.
> 
> Note: Media queries are very helpful here.

Seems there is a problem. Swipeable drawer require open state while the drawer is permanent, so maybe just to set drawer anchor to bottom while isn't enough space for left sidebar? Looks good at tablet and smartphone.

**Comment by vie10** [comment]
<img width="300" alt="Screenshot 2022-02-07 at 21 58 19" src="https://user-images.githubusercontent.com/81972035/152862294-53401d2d-9cb8-4e18-89fd-1e8721f39681.png">

**Comment by aerialist7** [comment]
Looks wierd, swipeable is way better. 
And of cause it should has a state. 
So for mobiles we need to show another component with its own specifics

**Comment by vie10** [comment]
> Looks wierd, swipeable is way better.
> And of cause it should has a state.
> So for mobiles we need to show another component with its own specifics

Seems you're right. I'll try it as possible

**Comment by vie10** [comment]
Will implemented in #9
